config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :playlists
  resources :users
  resources :playlist_songs
  
  post "/songs/:playlist_id/add_to_playlist", to: "songs#add_to_playlist", as: "add_to_playlist"
  post "/songs/add_to_songs", to: "songs#add_to_songs", as: "add_to_songs"
  post "/songs/sort_artist", to: "songs#sort_artist", as: "sort_artist"
  post "/songs/sort_title", to: "songs#sort_title", as: "sort_title"
  get "/songs/:id/:playlist_id", to: "songs#show"
  delete "/playlist_songs/:playlist_id/:song_id", to: "playlist_songs#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
  validates :name, uniqueness: {message: "( ゜-゜) ...there is already a Playlist with that name"}
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist, required: false
  belongs_to :song, required: false
  belongs_to :user, required: false
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :playlist_songs, dependent: :destroy
  has_many :users, through: :playlists
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists, dependent: :destroy
  has_many :songs, through: :playlist_songs
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController

  def index
    @playlist_songs = PlaylistSong.all.uniq(&:song_id)
  end

  def destroy
    @playlist_song = PlaylistSong.find_by(playlist_id: params[:playlist_id], song_id: params[:song_id])
    @playlist_song.destroy
    redirect_to request.referrer
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlists = Playlist.all
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :index
    end
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    @playlist.update(playlist_params)
    redirect_to @playlist
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    redirect_to playlists_path
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name, :user_id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
    if !params[:playlist_id].blank?
      @playlist = Playlist.find(params[:playlist_id])
    end
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    redirect_to @song
  end

  def add_to_playlist
    artist = params[:artist].titleize
    title = params[:title].titleize
    begin
      result = RestClient.get("https://api.lyrics.ovh/v1/#{artist.gsub(/\s/, "+")}/#{title.gsub(/\s/, "+")}")
    rescue RestClient::NotFound => e
      flash[:alert] = " ¯\\(◉_◉)/¯ Song was not found. Please try a different spelling, or a different song!"
      redirect_to playlist_path(params[:playlist_id])
    else
      resp_hash = JSON.parse(result.body)
      lyrics = resp_hash["lyrics"]
      if !Song.find_by(title: title, artist: artist)
        @song = Song.create(title: title, artist: artist, lyrics: lyrics)
        @playlist_song = PlaylistSong.create(playlist_id: params[:playlist_id], song_id: @song.id)
        flash[:notice] = "(>ﾟヮﾟ)> Song has been added! <(ﾟヮﾟ<)"
        redirect_to request.referrer
      else
        @song = Song.find_by(title: title, artist: artist)
        if !PlaylistSong.find_by(playlist_id: params[:playlist_id], song_id: @song.id)
          @playlist_song = PlaylistSong.create(playlist_id: params[:playlist_id], song_id: @song.id)
          flash[:notice] = "(>ﾟヮﾟ)> Song has been added! <(ﾟヮﾟ<)"
          redirect_to request.referrer
        else
          flash[:alert] = "(；￣ .￣）...this song is already in playlist!"
          redirect_to request.referrer
        end
      end
    end
  end

  def add_to_songs
    artist = params[:artist].titleize
    title = params[:title].titleize
    begin
      result = RestClient.get("https://api.lyrics.ovh/v1/#{artist.gsub(/\s/, "+")}/#{title.gsub(/\s/, "+")}")
    rescue RestClient::NotFound => e
      flash[:alert] = " ¯\\(◉_◉)/¯ Song was not found. Please try a different spelling, or a different song!"
      redirect_to songs_path
    else
      resp_hash = JSON.parse(result.body)
      lyrics = resp_hash["lyrics"]
      if !Song.find_by(title: title, artist: artist)
        @song = Song.create(title: title, artist: artist, lyrics: lyrics)
        flash[:notice] = "(>ﾟヮﾟ)> Song has been added! <( ﾟヮﾟ<)"
        redirect_to request.referrer
      else
        flash[:alert] = "(；￣ .￣）...this song is already in the vault"
        redirect_to request.referrer
      end
    end
  end

  def sort_artist
    @songs = Song.all.sort_by(&:artist)
    render :index
  end

  def sort_title
    @songs = Song.all.sort_by(&:title)
    render :index
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title, :artist, :lyrics, :video_url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlist_songs_helper.rb
module PlaylistSongsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironModTwoProjectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Mukta&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sen&display=swap" rel="stylesheet">
  </head>

  <body>
  <header>
    <%= link_to 'Playlists', playlists_path, class: "header_playlist" %> <div class="pole">|</div> 
    <%= link_to 'Song Vault', songs_path, class: "header_song" %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/playlist_songs/index.html.erb
<div class="playlists_background">
<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>
<h1>Songs from all Playlists</h1>
<div class="edit_song"><%= link_to "Return to Playlists", playlists_path %></div>
<br>

<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<% @playlist_songs.each do |playlist_song| %>
  <ul>
    <li><%= link_to "#{playlist_song.song.artist} - #{playlist_song.song.title} || Playlist: #{playlist_song.playlist.name}", song_path(playlist_song.song.id) %></li>
  </ul>
<% end %>

<br></br>
</div>

app/views/playlists/edit.html.erb
<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>
<%= form_for @playlist do |f| %>
  <%= f.label "Playlist Name:" %>
  <%= f.text_field :name %><br>
  <%= f.submit 'Create' %>
<% end %>

app/views/playlists/index.html.erb
<div class="playlists_background">

<h1 class="kara">KARA-OK!</h1>
<div id="playlisthead"><h1>Playlists |</h1><h2><%= link_to "Playlist Songs", playlist_songs_path %></h2></div>
<h3>Create New Playlist</h3>
<%= form_for @playlist do |f| %>
  <%= f.label "Playlist Name" %>
  <%= f.text_field :name %>

  <%= f.collection_select :user_id, User.all, :id, :username, class: "profile_select" %>
  <%= f.submit 'Create Playlist', class: "button" %>
<% end %>
<br>
<% if @playlist.errors.any? %>
  <div class="error" %>
    <%= @playlist.errors[:name].first %>
  </div>
  <% end %>
<br>
<% @playlists.each do |playlist| %>
    <h4><%= link_to "#{playlist.name}", playlist_path(playlist) %></h4>
      <% playlist.songs[0..2].each do |song| %>
      <ul>
        <li><%= link_to "#{song.artist} - #{song.title}", "/songs/#{song.id}/#{playlist.id}", method: "get" %></li>
      </ul>
      <% end %>
      <br>
<% end %>

<br></br>
</div>

app/views/playlists/show.html.erb
<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>
<div class="playlist_background">

  <h1><%= @playlist.name %></h1>
  <h3>Add Song to Playlist</h3>
    <%= form_tag add_to_playlist_path(@playlist.id) do %>
      <label>Artist <%= text_field_tag :artist %>
        Title <%= text_field_tag :title %>
        <% hidden_field_tag :playlist_id, @playlist.id %>
      <%= submit_tag "Add Song", class: "button" %>
    <% end %>
<br>
<br>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if @playlist.songs == [] %>
  <h3>No Songs</h3>
<% else %>
  <h3>Songs</h3>
  <% @playlist.songs.each do |song| %>
    <ul>
      <li><%= link_to "#{song.artist} - #{song.title}", "/songs/#{song.id}/#{@playlist.id}", method: "get" %></li>
      <%= button_to "Remove Song", "/playlist_songs/#{@playlist.id}/#{song.id}", method: :delete, data: {confirm: "Are you sure you want to remove?" }, class: "button" %>
    </ul>
  <% end %>
<% end %>

<br></br>
<br></br>
<%= button_to 'Delete Playlist', playlist_path(@playlist), data: {:confirm => 'Are you sure?'}, :method => :delete, data: {confirm: "Are you sure you want to remove?" }, class: "delete_button" %>

<br></br>
</div>

app/views/songs/edit.html.erb
<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>
<div class="song_background">
<h1><%= @song.artist %> - <%= @song.title %></h1>
<div class="edit_song"><%= link_to 'Return to Previous', song_path(@song) %></div>

<br>
<%= form_for @song do |f| %>

  <div class="edit_video">
    Youtube url <%= f.text_field :video_url %>
  </div>
  <br>
  Lyrics<br>
  <div class="lyrics"><%= f.text_area :lyrics %></div>
  <br>

  <%= f.submit class: "delete_button"%>
<% end %>

<br></br>
</div>

app/views/songs/index.html.erb
<div class="playlists_background">
<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>
<h1>Song Vault</h1>

<h3>Add Song to Repetoire</h3>
<%= form_tag add_to_songs_path do %>
  <label>Artist </label><%= text_field_tag :artist %>
  Title <%= text_field_tag :title %>
  <%= submit_tag "Add Song", class: "button" %>
<% end %>
<br>

<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<%= button_to "Sort by Artist", sort_artist_path, method: "post", class: "button" %>
<%= button_to "Sort by Title", sort_title_path, method: "post", class: "button" %>
<% @songs.each do |song| %>
  <ul>
    <li><%= link_to "#{song.artist} - #{song.title}", song_path(song) %></li>
  </ul>
<% end %>

<br></br>
</div>

app/views/songs/show.html.erb
<div class="song_background">
<div class="show_title"><h1><%= @song.artist %> - <%= @song.title %></h1></div>
<div class="edit_song"><%= link_to "Edit Song", edit_song_path(@song) %></div>
  <br>
  <% if defined?(@playlist) %>
    <div class="edit_song"><%= link_to "Return to Playlist", playlist_path(@playlist) %></div>
  <% end %>
  <br>
  <div class="lyrics_container">
    <div class="lyrics_show"><%= @song.lyrics.gsub(/[\r\n]+/, '<br><br>').html_safe %></div>
    <div id="video">
      <% if !@song.video_url.blank? %>
        <iframe id="iframe_main" width="560" height="315" src="https://www.youtube.com/embed/<%= @song.video_url.match(/\w+$/).to_s %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
    </div>
  </div>

<br></br>
<br></br>
  <%= button_to 'Delete Song', song_path(@song), data: {:confirm => 'Are you sure?'}, :method => :delete, data: {confirm: "Are you sure you want to remove?" }, class: "delete_button" %>
<br></br>
<br></br>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label "Name: " %>
  <%= f.text_field :username %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2><%= link_to 'Playlists', playlists_path %>

<div id="centerhead"><h1 class="kara">KARA-OK!</h1></div>

<h2><%= link_to 'Songs', songs_path %>

<h3>Playlists</h3>

<% @user.playlists.each do |playlist| %>

<h4><%= link_to "#{playlist.name}", playlist_path(playlist) %></h4>
  <ul>
    <% playlist.songs[0..9].each do |song| %>
      <li><%= link_to "#{song.artist} - #{song.title}", song_path(song) %></li>
    <% end %>
  </ul>
<% end %>

<h3><%= link_to 'Create Playlist', new_playlist_path %></h3>
<h3><%= link_to 'Search Song', new_song_path %></h3>